CREATE TABLE IF NOT EXISTS games (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    illustration TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    gameId INTEGER NOT NULL,
    gameMasterId INTEGER NOT NULL,
    date DATE,
    FOREIGN KEY (gameId) REFERENCES games (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS participations (
    sessionId INTEGER NOT NULL,
    playerId INTEGER NOT NULL,
    FOREIGN KEY (sessionId) REFERENCES sessions (id) ON DELETE CASCADE ON UPDATE CASCADE
)
