services:
    bot:
        image: ghcr.io/swiip/rpg-club-app-bot:latest
        container_name: rpg-club-bot
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
        volumes:
            - bot-data:/app/db:rw
        user: "1001:0"
        restart: unless-stopped

    watchtower:
        image: containrrr/watchtower:arm64v8-latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        command: --interval 30 --cleanup

volumes:
    bot-data:
        name: rpg-club-bot-data
