

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."campaign" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "game" bigint NOT NULL,
    "gm" bigint
);


ALTER TABLE "public"."campaign" OWNER TO "postgres";


ALTER TABLE "public"."campaign" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."campaign_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "illustration" character varying
);


ALTER TABLE "public"."game" OWNER TO "postgres";


ALTER TABLE "public"."game" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."member" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "handle" character varying
);


ALTER TABLE "public"."member" OWNER TO "postgres";


ALTER TABLE "public"."member" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."member_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."os" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "gm" bigint,
    "game" bigint,
    "date" "date"
);


ALTER TABLE "public"."os" OWNER TO "postgres";


ALTER TABLE "public"."os" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."os_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."registration" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "member" bigint,
    "os" bigint,
    "campaign" bigint,
    "confirmation" boolean
);


ALTER TABLE "public"."registration" OWNER TO "postgres";


ALTER TABLE "public"."registration" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."registration_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."campaign"
    ADD CONSTRAINT "campaign_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game"
    ADD CONSTRAINT "game_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."member"
    ADD CONSTRAINT "member_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."os"
    ADD CONSTRAINT "os_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registration"
    ADD CONSTRAINT "registration_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."campaign"
    ADD CONSTRAINT "campaign_game_fkey" FOREIGN KEY ("game") REFERENCES "public"."game"("id");



ALTER TABLE ONLY "public"."campaign"
    ADD CONSTRAINT "campaign_gm_fkey" FOREIGN KEY ("gm") REFERENCES "public"."member"("id");



ALTER TABLE ONLY "public"."os"
    ADD CONSTRAINT "os_game_fkey" FOREIGN KEY ("game") REFERENCES "public"."game"("id");



ALTER TABLE ONLY "public"."os"
    ADD CONSTRAINT "os_gm_fkey" FOREIGN KEY ("gm") REFERENCES "public"."member"("id");



ALTER TABLE ONLY "public"."registration"
    ADD CONSTRAINT "registration_campaign_fkey" FOREIGN KEY ("campaign") REFERENCES "public"."campaign"("id");



ALTER TABLE ONLY "public"."registration"
    ADD CONSTRAINT "registration_member_fkey" FOREIGN KEY ("member") REFERENCES "public"."member"("id");



ALTER TABLE ONLY "public"."registration"
    ADD CONSTRAINT "registration_os_fkey" FOREIGN KEY ("os") REFERENCES "public"."os"("id");



ALTER TABLE "public"."campaign" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."member" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."os" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."registration" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."campaign" TO "anon";
GRANT ALL ON TABLE "public"."campaign" TO "authenticated";
GRANT ALL ON TABLE "public"."campaign" TO "service_role";



GRANT ALL ON SEQUENCE "public"."campaign_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."campaign_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."campaign_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game" TO "anon";
GRANT ALL ON TABLE "public"."game" TO "authenticated";
GRANT ALL ON TABLE "public"."game" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."member" TO "anon";
GRANT ALL ON TABLE "public"."member" TO "authenticated";
GRANT ALL ON TABLE "public"."member" TO "service_role";



GRANT ALL ON SEQUENCE "public"."member_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."member_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."member_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."os" TO "anon";
GRANT ALL ON TABLE "public"."os" TO "authenticated";
GRANT ALL ON TABLE "public"."os" TO "service_role";



GRANT ALL ON SEQUENCE "public"."os_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."os_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."os_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."registration" TO "anon";
GRANT ALL ON TABLE "public"."registration" TO "authenticated";
GRANT ALL ON TABLE "public"."registration" TO "service_role";



GRANT ALL ON SEQUENCE "public"."registration_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."registration_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."registration_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
