name: Rust CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    setup:
        uses: ./.github/workflows/setup.yaml

    check:
        name: Check
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Check format
              run: cargo fmt --all -- --check
            - name: Check clippy
              run: cargo clippy -- -D warnings
            - name: Run tests
              run: cargo test

    build:
        name: Build
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: cargo build
